apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-gateway-service
  labels:
    app: spring-boot-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-gateway-service
  template:
    metadata:
      labels:
        app: spring-boot-gateway-service
    spec:
      containers:
      - name: gateway
        image: subhakarkotta/spring-boot-gateway-service:1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-gateway-service
  labels:
    app: spring-boot-gateway-service
    spring-boot: "true"
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: spring-boot-gateway-service
  type: LoadBalancer
